version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

    labels:
      - "dependencies"

    ignore:
      - dependency-name: "next-themes"
        versions:
          - "0.3.0"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
