github: [thedaviddias]
patreon: thedaviddias
open_collective: # Collective unavailable
ko_fi: thedaviddias
liberapay: # Replace with a single Liberapay username
issuehunt: # disabled
otechie: # Replace with a single Otechie username
