name: Production deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RAINDROP_COLLECTION: ${{ secrets.RAINDROP_COLLECTION }}
      RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}

    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.10.0
      #   with:
      #     access_token: ${{ github.token }}

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Detect Node version
        run: echo "##[set-output name=version;]$(cat .nvmrc)"
        id: nvmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.version }}'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run build
        run: pnpm build

      # - name: Run tests
      #   run: pnpm test:e2e

      # - name: SimpleLocalize Download
      #   uses: simplelocalize/download@latest
      #   with:
      #     apiKey: ${{ secrets.SIMPLE_LOCALIZE_KEY }}
      #     downloadPath: ./locales/{lang}/{ns}.json
      #     downloadFormat: single-language-json
      #     uploadOptions: 'WRITE_NESTED,ESCAPE_NEW_LINES'

      # - name: Vercel deployment
      #   uses: amondnet/vercel-action@v25.1.1
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-args: '--prod'
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
